name: Bun test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bun-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      - run: bun install
      - run: bun test
      - name: publish code coverage
        uses: paambaati/codeclimate-action@f429536ee076d758a24705203199548125a28ca7 # v9.0.0
        env:
          CC_TEST_REPORTER_ID: 7ab37ceb79625ff306e05fcea62a7b91d3722b64b3dcff8a48dbc8de4275f768
