name: attach bun .lockb file diff comment 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bun-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: koki-develop/bun-diff-action@v1
